import assert from 'node:assert/strict';
import { formLabel as computeFormLabel } from '../ui/speciesForms.ts';
import fs from 'node:fs';
const verified=JSON.parse(fs.readFileSync('ui/data/species-form-rules.json'));
const formLabel=(catalog,id,t,options={})=>computeFormLabel(catalog,id,t,{...options,verified});
const t=k=>k;
const family={species:[386,1128,1129,1130],offset:100};
const catalog={profile:{md5:'59c658a1081f542086de1060bb65f0b3',sprite_rules:{unown_species:201}},species:[386,920,921,1128,1129,1130].map(id=>({id,name:'代欧奇希斯'})),items:[{id:307,name:'超梦石X'},{id:308,name:'超梦石Y'}],form_families:[family],battle_forms:[{source:150,target:990,kind:'mega',trigger:{kind:'held_item',id:307}},{source:150,target:991,kind:'mega',trigger:{kind:'held_item',id:308}}]};
const snapshot=JSON.stringify(catalog);
for(const [id,key]of [[386,'formNormal'],[1128,'formAttack'],[1129,'formDefense'],[1130,'formSpeed']])assert.equal(formLabel(catalog,id,t),key);
for(const id of [920,921])assert.equal(formLabel(catalog,id,t),'formSameName');
assert.equal(formLabel(catalog,990,t),'mega X');
assert.equal(formLabel(catalog,991,t),'mega Y');
assert.equal(formLabel(catalog,150,t),'formBase');
assert.equal(formLabel({...catalog,profile:{md5:'another-rom'}},1128,t),'formVariant');
assert.equal(formLabel({...catalog,form_families:[]},1128,t),'formSameName');
const label={form:'攻击形态',decision:{status:'comparison',target:'386:攻击形态'}};
assert.equal(formLabel(catalog,920,t,{approved:label}),'formSameName');
assert.equal(formLabel(catalog,920,t,{approved:{...label,decision:{...label.decision,status:'direct'}}}),'攻击形态');
for(const [pid,char]of [[0,'A'],[1,'B'],[0x1000000,'I'],[0x10202,'!'],[0x10203,'?']])assert.equal(formLabel(catalog,201,t,{pid}),char);
assert.equal(JSON.stringify(catalog),snapshot);
console.log('Passed: ROM-verified Deoxys, ambiguous same-name entries, Mega X/Y triggers, PID letters, mapping semantics, cross-ROM isolation and no mutation.');
