import assert from 'node:assert/strict';
import { evolutionGraph } from '../ui/evolutionGraph.ts';
const edge=(source,target,parameter=1,offset=1)=>({source,target,method:7,condition:'item',parameter,offset});
const detail={species:{id:25},evolutions:[],relations:{species:[25,26,172,1048,1083,1084,1097,1386],evolutions:[edge(25,26),edge(25,26,1,2),edge(25,26,2,3),edge(25,1048),edge(172,25),edge(1048,26),edge(26,1386)],battle_forms:[],form_families:[{species:[25,1083,1084],offset:1},{species:[26,1048],offset:2},{species:[172,1097],offset:3},{species:[25,1083,1084],offset:4}],name_relations:[]}};
const before=JSON.stringify(detail);
const all=v=>[...v.main,...v.battleIds,...v.families.flatMap(f=>f.members),...v.nameIds];
let graph=evolutionGraph(detail);
assert.equal(all(graph).length,8);
assert.equal(new Set(all(graph)).size,8);
assert.equal(graph.evolutions.filter(e=>e.source===25&&e.target===26).length,2,'different conditions remain, duplicate ROM records merge');
assert.equal(graph.main[0],172);
assert.equal(graph.families.length,2,'already shown Raichu family and duplicate family removed');
assert.equal(JSON.stringify(detail),before,'presentation must not modify ROM relations');
const cycle=structuredClone(detail);cycle.relations.evolutions.push(edge(26,25));
assert.equal(new Set(all(evolutionGraph(cycle))).size,8,'cycles do not duplicate nodes');
const mega={source:9,target:980,kind:'mega',trigger:{kind:'held_item',id:297},offset:1};
const forms={species:{id:980},evolutions:[],relations:{species:[9,980,899],evolutions:[],battle_forms:[mega,{...mega,offset:2}],form_families:[{species:[9,980],offset:3}],name_relations:[{source:9,target:899},{source:9,target:899}]}};
graph=evolutionGraph(forms);assert.deepEqual(all(graph),[9,980,899]);assert.equal(graph.battles.length,1);assert.equal(graph.families.length,0);
assert.deepEqual(evolutionGraph({species:{id:1},evolutions:[]}).main,[1]);
console.log('Passed: unique species cards, retained alternative conditions, cycles, overlapping families, Mega/name-link deduplication and immutable inputs.');
